cc_binary(
    name = "hello_world_c",  # 実行するバイナリの名前
    srcs = ["src/c/main.c"],     # ソースファイル
)

cc_binary(
    name = "hello_world_cpp",  # 実行するバイナリの名前
    srcs = ["src/cpp/main.cpp"],   # ソースファイル
)